### PR TITLE
[Canvas V2][4/n] Migrate hover and context menus

### LINKED ISSUE #11: Random Tooltip Behavior
The on hover behavior of some canvas elements doesn't show tooltips as intended, most visible on the timing "dots" where the menu has stopped rendering at all.

Steps to reproduce:
- Run the prototype.
- Hover around work chunks and dots. 

The unaligned tooltip behavior might be related to unaligned flamegraphs.

### PR DESCRIPTION
**Pull request by taneliang**
Stacked on #33. Part of #30.

* Fixes the non-working hover and context menus.
* Adds support for new react event types.

Also seems to unintentionally fix #11, but more testing needed to confirm this.

## Test Plan

(New) Event hover:
image

Measure hover. Also test that hovering still picks the top event:
image

Hover after panning:
image

Hover at edge of screen:
image

Context menu "Zoom to batch" leaves a gap on the left for the priority labels. This needs to be fixed in CanvasPage once #29 is implemented:
image

Fixed (from previous PR in stack) flamegraph hover:
image

Copy summary:
image

Copy component stack:
image

Copy component name:
image

### CODE REVIEW

File: src/EventTooltip.js [hunk 1]
```diff
@@ -163,9 +161,18 @@ const TooltipReactEvent = ({
     case 'schedule-state-update':
       label = 'state update scheduled';
       break;
-    case 'suspend':
+    case 'schedule-force-update':
```
Comment (jevakallio) [inline src/EventTooltip.js:164]: This is very much a code style suggestion and out of scope for this PR, but I much prefer these types of mapping switches to be extracted to their own functions (e.g. `getEventTypeLabelText(type)`), instead of mutating a local variable.

File: src/EventTooltip.js [hunk 2]
```diff
@@ -114,11 +116,9 @@ function formatComponentStack(componentStack: string): string {
 }
 
 const TooltipFlamechartNode = ({
```
Comment (jevakallio) [inline src/EventTooltip.js:118]: Not part of this diff, but happened to notice that the `COLORS.TOOLTIP_BG` and `COLORS.TOOLTIP` constants referenced in this function (ln 131-132) are not defined on `COLORS` according to flow (and my visual inspection), which may need to be addressed.

File: src/canvas/canvasUtils.js [hunk 3]
```diff
@@ -112,94 +112,100 @@ export const trimFlamegraphText = (
...
   }
 
-  if (canvasMouseY + offsetY < schedulerCanvasHeight) {
-    const adjustedCanvasMouseY = canvasMouseY - HEADER_HEIGHT_FIXED + offsetY;
-    let priorityMinY = HEADER_HEIGHT_FIXED;
-    let priorityIndex = null;
-    let priority: ReactPriority = 'unscheduled';
-    for (let index = 0; index < REACT_PRIORITIES.length; index++) {
-      priority = REACT_PRIORITIES[index];
+  if (canvasMouseY + offsetY < HEADER_HEIGHT_FIXED + EVENT_ROW_HEIGHT_FIXED) {
```
Comment (jevakallio) [inline src/canvas/canvasUtils.js:125]: Comments on these switch branches would make it a lot quicker to grok what's going on

**Review by jevakallio — APPROVED** [review]
Code quality wise this looks good. I would personally break down a lot of these functions into smaller ones, but that's a preference thing. I find that in many of these functions we end up doing quite low-level activities (like backwards loops with early exists via continue statements), which I'd much rather extract into a higher-order utility ("findLast..." or some such).

I wasn't able to run this PR due to missing scaffolding code, so it has not been tested.

File: src/canvas/canvasUtils.js (hunk 3 above)
Comment (taneliang) [reply src/canvas/canvasUtils.js:125]: I actually put the comment in the next line, to be consistent with where the comment had to go in the `else if` block below. Maybe it's not clear enough; let me think of another way

File: src/EventTooltip.js (hunk 1 above)
Comment (taneliang) [reply src/EventTooltip.js:164]: Filed as #37

File: src/EventTooltip.js (hunk 2 above)
Comment (taneliang) [reply src/EventTooltip.js:118]: Filed a more general issue to fix Flow types at #38. I've been ignoring the errors above as they haven't seemed to break anything, but we definitely will want to look at this again once the larger tasks are done.

**Comment by taneliang** [comment]
Rebased without changes

File: src/canvas/canvasUtils.js (hunk 3 above)
Comment (taneliang) [reply src/canvas/canvasUtils.js:125]: Okay, I've tried addressing this in https://github.com/MLH-Fellowship/scheduling-profiler-prototype/pull/40 by breaking this big function. The broken function should also better parallels the broken `renderCanvas` so I think it's much clearer

**Comment by taneliang** [comment]
Rebased on master

**Comment by taneliang** [comment]
Updated App.js and CanvasPage.js to pass V2 data into the functions/components changed in this PR
